import type { Metadata } from "next";
import "./globals.css";
import { NavBar } from "@/components/NavBar";
import { roboto_mono } from "@/ui/fonts";

export const dynamic = 'force-dynamic';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto_mono.className} antialiased flex w-full h-screen bg-neutral-800`}
      >
        <NavBar />
        <main className="flex-1 overflow-auto">
            {children}
        </main>
      </body>
    </html>
  );
}
